development:
  adapter: postgresql
  encoding: unicode
  database: dc5l6vsgefal2t
  pool: 5
  username: eqwytouydojkja
  password: oo3A5ybIkDa9IekpPNqVmB56I1
  port: 5432
test:
  adapter: postgresql
  encoding: unicode
  database: dc5l6vsgefal2t
  pool: 5
  username: eqwytouydojkja
  password: oo3A5ybIkDa9IekpPNqVmB56I1
  port: 5432
production:
  adapter: postgresql
  encoding: unicode
  database: dc5l6vsgefal2t
  pool: 5
  username: eqwytouydojkja
  password: oo3A5ybIkDa9IekpPNqVmB56I1
  port: 5432
