# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

#
#Post.create(titulo: 'Diseñador Web LAN.com', sueldo: 200000, descripcion: 'LATAM AIRLINES GROUP busca incorporar Diseñador Web Lan.com para su Gerencia Experiencia Usuario E-Business Latam. La mision del cargo es definir, revisar y actualizar lineamientos graficos para todas las interfaces de LAN.com y TAM.com.br con foco en aumentar la satisfaccion del usuario con un alto grado de creatividad e innovacion', funciones: 'Definir lineamientos graficos y de interaccion para LAN.com y TAM.com.br, portales, minisitios y otras plataformas tales como mobile basados en buenas practicas, personalidad de la marca (principios de diseño) y metricas. - Participar de proyectos creando multiples prototipos de diseño, apoyando en la toma de decisiones y definiciones para diseño de informacion y flujos de interaccion. - Desarrollar propuestas creativas para la mejora continua del sitio.', requisitos: 'ultimo año de carrera...')
#Post.create(titulo: 'Diseñador Web LAN.com', sueldo: 200000, descripcion: 'LATAM AIRLINES GROUP busca incorporar Diseñador Web Lan.com para su Gerencia Experiencia Usuario E-Business Latam. La mision del cargo es definir, revisar y actualizar lineamientos graficos para todas las interfaces de LAN.com y TAM.com.br con foco en aumentar la satisfaccion del usuario con un alto grado de creatividad e innovacion', funciones: 'Definir lineamientos graficos y de interaccion para LAN.com y TAM.com.br, portales, minisitios y otras plataformas tales como mobile basados en buenas practicas, personalidad de la marca (principios de diseño) y metricas. - Participar de proyectos creando multiples prototipos de diseño, apoyando en la toma de decisiones y definiciones para diseño de informacion y flujos de interaccion. - Desarrollar propuestas creativas para la mejora continua del sitio.', requisitos: 'ultimo año de carrera...')
#Post.create(titulo: 'Diseñador Web LAN.com', sueldo: 200000, descripcion: 'LATAM AIRLINES GROUP busca incorporar Diseñador Web Lan.com para su Gerencia Experiencia Usuario E-Business Latam. La mision del cargo es definir, revisar y actualizar lineamientos graficos para todas las interfaces de LAN.com y TAM.com.br con foco en aumentar la satisfaccion del usuario con un alto grado de creatividad e innovacion', funciones: 'Definir lineamientos graficos y de interaccion para LAN.com y TAM.com.br, portales, minisitios y otras plataformas tales como mobile basados en buenas practicas, personalidad de la marca (principios de diseño) y metricas. - Participar de proyectos creando multiples prototipos de diseño, apoyando en la toma de decisiones y definiciones para diseño de informacion y flujos de interaccion. - Desarrollar propuestas creativas para la mejora continua del sitio.', requisitos: 'ultimo año de carrera...')
#Post.create(titulo: 'Diseñador Web LAN.com', sueldo: 200000, descripcion: 'LATAM AIRLINES GROUP busca incorporar Diseñador Web Lan.com para su Gerencia Experiencia Usuario E-Business Latam. La mision del cargo es definir, revisar y actualizar lineamientos graficos para todas las interfaces de LAN.com y TAM.com.br con foco en aumentar la satisfaccion del usuario con un alto grado de creatividad e innovacion', funciones: 'Definir lineamientos graficos y de interaccion para LAN.com y TAM.com.br, portales, minisitios y otras plataformas tales como mobile basados en buenas practicas, personalidad de la marca (principios de diseño) y metricas. - Participar de proyectos creando multiples prototipos de diseño, apoyando en la toma de decisiones y definiciones para diseño de informacion y flujos de interaccion. - Desarrollar propuestas creativas para la mejora continua del sitio.', requisitos: 'ultimo año de carrera...')
#Post.create(titulo: 'Diseñador Web LAN.com', sueldo: 200000, descripcion: 'LATAM AIRLINES GROUP busca incorporar Diseñador Web Lan.com para su Gerencia Experiencia Usuario E-Business Latam. La mision del cargo es definir, revisar y actualizar lineamientos graficos para todas las interfaces de LAN.com y TAM.com.br con foco en aumentar la satisfaccion del usuario con un alto grado de creatividad e innovacion', funciones: 'Definir lineamientos graficos y de interaccion para LAN.com y TAM.com.br, portales, minisitios y otras plataformas tales como mobile basados en buenas practicas, personalidad de la marca (principios de diseño) y metricas. - Participar de proyectos creando multiples prototipos de diseño, apoyando en la toma de decisiones y definiciones para diseño de informacion y flujos de interaccion. - Desarrollar propuestas creativas para la mejora continua del sitio.', requisitos: 'ultimo año de carrera...')
#Post.create(titulo: 'Diseñador Web LAN.com', sueldo: 200000, descripcion: 'LATAM AIRLINES GROUP busca incorporar Diseñador Web Lan.com para su Gerencia Experiencia Usuario E-Business Latam. La mision del cargo es definir, revisar y actualizar lineamientos graficos para todas las interfaces de LAN.com y TAM.com.br con foco en aumentar la satisfaccion del usuario con un alto grado de creatividad e innovacion', funciones: 'Definir lineamientos graficos y de interaccion para LAN.com y TAM.com.br, portales, minisitios y otras plataformas tales como mobile basados en buenas practicas, personalidad de la marca (principios de diseño) y metricas. - Participar de proyectos creando multiples prototipos de diseño, apoyando en la toma de decisiones y definiciones para diseño de informacion y flujos de interaccion. - Desarrollar propuestas creativas para la mejora continua del sitio.', requisitos: 'ultimo año de carrera...')
#Post.create(titulo: 'Diseñador Web LAN.com', sueldo: 200000, descripcion: 'LATAM AIRLINES GROUP busca incorporar Diseñador Web Lan.com para su Gerencia Experiencia Usuario E-Business Latam. La mision del cargo es definir, revisar y actualizar lineamientos graficos para todas las interfaces de LAN.com y TAM.com.br con foco en aumentar la satisfaccion del usuario con un alto grado de creatividad e innovacion', funciones: 'Definir lineamientos graficos y de interaccion para LAN.com y TAM.com.br, portales, minisitios y otras plataformas tales como mobile basados en buenas practicas, personalidad de la marca (principios de diseño) y metricas. - Participar de proyectos creando multiples prototipos de diseño, apoyando en la toma de decisiones y definiciones para diseño de informacion y flujos de interaccion. - Desarrollar propuestas creativas para la mejora continua del sitio.', requisitos: 'ultimo año de carrera...')
#Post.create(titulo: 'Diseñador Web LAN.com', sueldo: 200000, descripcion: 'LATAM AIRLINES GROUP busca incorporar Diseñador Web Lan.com para su Gerencia Experiencia Usuario E-Business Latam. La mision del cargo es definir, revisar y actualizar lineamientos graficos para todas las interfaces de LAN.com y TAM.com.br con foco en aumentar la satisfaccion del usuario con un alto grado de creatividad e innovacion', funciones: 'Definir lineamientos graficos y de interaccion para LAN.com y TAM.com.br, portales, minisitios y otras plataformas tales como mobile basados en buenas practicas, personalidad de la marca (principios de diseño) y metricas. - Participar de proyectos creando multiples prototipos de diseño, apoyando en la toma de decisiones y definiciones para diseño de informacion y flujos de interaccion. - Desarrollar propuestas creativas para la mejora continua del sitio.', requisitos: 'ultimo año de carrera...')
#Post.create(titulo: 'Diseñador Web LAN.com', sueldo: 200000, descripcion: 'LATAM AIRLINES GROUP busca incorporar Diseñador Web Lan.com para su Gerencia Experiencia Usuario E-Business Latam. La mision del cargo es definir, revisar y actualizar lineamientos graficos para todas las interfaces de LAN.com y TAM.com.br con foco en aumentar la satisfaccion del usuario con un alto grado de creatividad e innovacion', funciones: 'Definir lineamientos graficos y de interaccion para LAN.com y TAM.com.br, portales, minisitios y otras plataformas tales como mobile basados en buenas practicas, personalidad de la marca (principios de diseño) y metricas. - Participar de proyectos creando multiples prototipos de diseño, apoyando en la toma de decisiones y definiciones para diseño de informacion y flujos de interaccion. - Desarrollar propuestas creativas para la mejora continua del sitio.', requisitos: 'ultimo año de carrera...')
#Post.create(titulo: 'Diseñador Web LAN.com', sueldo: 200000, descripcion: 'LATAM AIRLINES GROUP busca incorporar Diseñador Web Lan.com para su Gerencia Experiencia Usuario E-Business Latam. La mision del cargo es definir, revisar y actualizar lineamientos graficos para todas las interfaces de LAN.com y TAM.com.br con foco en aumentar la satisfaccion del usuario con un alto grado de creatividad e innovacion', funciones: 'Definir lineamientos graficos y de interaccion para LAN.com y TAM.com.br, portales, minisitios y otras plataformas tales como mobile basados en buenas practicas, personalidad de la marca (principios de diseño) y metricas. - Participar de proyectos creando multiples prototipos de diseño, apoyando en la toma de decisiones y definiciones para diseño de informacion y flujos de interaccion. - Desarrollar propuestas creativas para la mejora continua del sitio.', requisitos: 'ultimo año de carrera...')
#Post.create(titulo: 'Diseñador Web LAN.com', sueldo: 200000, descripcion: 'LATAM AIRLINES GROUP busca incorporar Diseñador Web Lan.com para su Gerencia Experiencia Usuario E-Business Latam. La mision del cargo es definir, revisar y actualizar lineamientos graficos para todas las interfaces de LAN.com y TAM.com.br con foco en aumentar la satisfaccion del usuario con un alto grado de creatividad e innovacion', funciones: 'Definir lineamientos graficos y de interaccion para LAN.com y TAM.com.br, portales, minisitios y otras plataformas tales como mobile basados en buenas practicas, personalidad de la marca (principios de diseño) y metricas. - Participar de proyectos creando multiples prototipos de diseño, apoyando en la toma de decisiones y definiciones para diseño de informacion y flujos de interaccion. - Desarrollar propuestas creativas para la mejora continua del sitio.', requisitos: 'ultimo año de carrera...')
#Post.create(titulo: 'Diseñador Web LAN.com', sueldo: 200000, descripcion: 'LATAM AIRLINES GROUP busca incorporar Diseñador Web Lan.com para su Gerencia Experiencia Usuario E-Business Latam. La mision del cargo es definir, revisar y actualizar lineamientos graficos para todas las interfaces de LAN.com y TAM.com.br con foco en aumentar la satisfaccion del usuario con un alto grado de creatividad e innovacion', funciones: 'Definir lineamientos graficos y de interaccion para LAN.com y TAM.com.br, portales, minisitios y otras plataformas tales como mobile basados en buenas practicas, personalidad de la marca (principios de diseño) y metricas. - Participar de proyectos creando multiples prototipos de diseño, apoyando en la toma de decisiones y definiciones para diseño de informacion y flujos de interaccion. - Desarrollar propuestas creativas para la mejora continua del sitio.', requisitos: 'ultimo año de carrera...')
#Post.create(titulo: 'Diseñador Web LAN.com', sueldo: 200000, descripcion: 'LATAM AIRLINES GROUP busca incorporar Diseñador Web Lan.com para su Gerencia Experiencia Usuario E-Business Latam. La mision del cargo es definir, revisar y actualizar lineamientos graficos para todas las interfaces de LAN.com y TAM.com.br con foco en aumentar la satisfaccion del usuario con un alto grado de creatividad e innovacion', funciones: 'Definir lineamientos graficos y de interaccion para LAN.com y TAM.com.br, portales, minisitios y otras plataformas tales como mobile basados en buenas practicas, personalidad de la marca (principios de diseño) y metricas. - Participar de proyectos creando multiples prototipos de diseño, apoyando en la toma de decisiones y definiciones para diseño de informacion y flujos de interaccion. - Desarrollar propuestas creativas para la mejora continua del sitio.', requisitos: 'ultimo año de carrera...')
#Post.create(titulo: 'Diseñador Web LAN.com', sueldo: 200000, descripcion: 'LATAM AIRLINES GROUP busca incorporar Diseñador Web Lan.com para su Gerencia Experiencia Usuario E-Business Latam. La mision del cargo es definir, revisar y actualizar lineamientos graficos para todas las interfaces de LAN.com y TAM.com.br con foco en aumentar la satisfaccion del usuario con un alto grado de creatividad e innovacion', funciones: 'Definir lineamientos graficos y de interaccion para LAN.com y TAM.com.br, portales, minisitios y otras plataformas tales como mobile basados en buenas practicas, personalidad de la marca (principios de diseño) y metricas. - Participar de proyectos creando multiples prototipos de diseño, apoyando en la toma de decisiones y definiciones para diseño de informacion y flujos de interaccion. - Desarrollar propuestas creativas para la mejora continua del sitio.', requisitos: 'ultimo año de carrera...')
#Post.create(titulo: 'Diseñador Web LAN.com', sueldo: 200000, descripcion: 'LATAM AIRLINES GROUP busca incorporar Diseñador Web Lan.com para su Gerencia Experiencia Usuario E-Business Latam. La mision del cargo es definir, revisar y actualizar lineamientos graficos para todas las interfaces de LAN.com y TAM.com.br con foco en aumentar la satisfaccion del usuario con un alto grado de creatividad e innovacion', funciones: 'Definir lineamientos graficos y de interaccion para LAN.com y TAM.com.br, portales, minisitios y otras plataformas tales como mobile basados en buenas practicas, personalidad de la marca (principios de diseño) y metricas. - Participar de proyectos creando multiples prototipos de diseño, apoyando en la toma de decisiones y definiciones para diseño de informacion y flujos de interaccion. - Desarrollar propuestas creativas para la mejora continua del sitio.', requisitos: 'ultimo año de carrera...')
#Post.create(titulo: 'Diseñador Web LAN.com', sueldo: 200000, descripcion: 'LATAM AIRLINES GROUP busca incorporar Diseñador Web Lan.com para su Gerencia Experiencia Usuario E-Business Latam. La mision del cargo es definir, revisar y actualizar lineamientos graficos para todas las interfaces de LAN.com y TAM.com.br con foco en aumentar la satisfaccion del usuario con un alto grado de creatividad e innovacion', funciones: 'Definir lineamientos graficos y de interaccion para LAN.com y TAM.com.br, portales, minisitios y otras plataformas tales como mobile basados en buenas practicas, personalidad de la marca (principios de diseño) y metricas. - Participar de proyectos creando multiples prototipos de diseño, apoyando en la toma de decisiones y definiciones para diseño de informacion y flujos de interaccion. - Desarrollar propuestas creativas para la mejora continua del sitio.', requisitos: 'ultimo año de carrera...')
#Post.create(titulo: 'Diseñador Web LAN.com', sueldo: 200000, descripcion: 'LATAM AIRLINES GROUP busca incorporar Diseñador Web Lan.com para su Gerencia Experiencia Usuario E-Business Latam. La mision del cargo es definir, revisar y actualizar lineamientos graficos para todas las interfaces de LAN.com y TAM.com.br con foco en aumentar la satisfaccion del usuario con un alto grado de creatividad e innovacion', funciones: 'Definir lineamientos graficos y de interaccion para LAN.com y TAM.com.br, portales, minisitios y otras plataformas tales como mobile basados en buenas practicas, personalidad de la marca (principios de diseño) y metricas. - Participar de proyectos creando multiples prototipos de diseño, apoyando en la toma de decisiones y definiciones para diseño de informacion y flujos de interaccion. - Desarrollar propuestas creativas para la mejora continua del sitio.', requisitos: 'ultimo año de carrera...')
#Post.create(titulo: 'Diseñador Web LAN.com', sueldo: 200000, descripcion: 'LATAM AIRLINES GROUP busca incorporar Diseñador Web Lan.com para su Gerencia Experiencia Usuario E-Business Latam. La mision del cargo es definir, revisar y actualizar lineamientos graficos para todas las interfaces de LAN.com y TAM.com.br con foco en aumentar la satisfaccion del usuario con un alto grado de creatividad e innovacion', funciones: 'Definir lineamientos graficos y de interaccion para LAN.com y TAM.com.br, portales, minisitios y otras plataformas tales como mobile basados en buenas practicas, personalidad de la marca (principios de diseño) y metricas. - Participar de proyectos creando multiples prototipos de diseño, apoyando en la toma de decisiones y definiciones para diseño de informacion y flujos de interaccion. - Desarrollar propuestas creativas para la mejora continua del sitio.', requisitos: 'ultimo año de carrera...')
#Post.create(titulo: 'Diseñador Web LAN.com', sueldo: 200000, descripcion: 'LATAM AIRLINES GROUP busca incorporar Diseñador Web Lan.com para su Gerencia Experiencia Usuario E-Business Latam. La mision del cargo es definir, revisar y actualizar lineamientos graficos para todas las interfaces de LAN.com y TAM.com.br con foco en aumentar la satisfaccion del usuario con un alto grado de creatividad e innovacion', funciones: 'Definir lineamientos graficos y de interaccion para LAN.com y TAM.com.br, portales, minisitios y otras plataformas tales como mobile basados en buenas practicas, personalidad de la marca (principios de diseño) y metricas. - Participar de proyectos creando multiples prototipos de diseño, apoyando en la toma de decisiones y definiciones para diseño de informacion y flujos de interaccion. - Desarrollar propuestas creativas para la mejora continua del sitio.', requisitos: 'ultimo año de carrera...')
#Post.create(titulo: 'Diseñador Web LAN.com', sueldo: 200000, descripcion: 'LATAM AIRLINES GROUP busca incorporar Diseñador Web Lan.com para su Gerencia Experiencia Usuario E-Business Latam. La mision del cargo es definir, revisar y actualizar lineamientos graficos para todas las interfaces de LAN.com y TAM.com.br con foco en aumentar la satisfaccion del usuario con un alto grado de creatividad e innovacion', funciones: 'Definir lineamientos graficos y de interaccion para LAN.com y TAM.com.br, portales, minisitios y otras plataformas tales como mobile basados en buenas practicas, personalidad de la marca (principios de diseño) y metricas. - Participar de proyectos creando multiples prototipos de diseño, apoyando en la toma de decisiones y definiciones para diseño de informacion y flujos de interaccion. - Desarrollar propuestas creativas para la mejora continua del sitio.', requisitos: 'ultimo año de carrera...')
#Post.create(titulo: 'Diseñador Web LAN.com', sueldo: 200000, descripcion: 'LATAM AIRLINES GROUP busca incorporar Diseñador Web Lan.com para su Gerencia Experiencia Usuario E-Business Latam. La mision del cargo es definir, revisar y actualizar lineamientos graficos para todas las interfaces de LAN.com y TAM.com.br con foco en aumentar la satisfaccion del usuario con un alto grado de creatividad e innovacion', funciones: 'Definir lineamientos graficos y de interaccion para LAN.com y TAM.com.br, portales, minisitios y otras plataformas tales como mobile basados en buenas practicas, personalidad de la marca (principios de diseño) y metricas. - Participar de proyectos creando multiples prototipos de diseño, apoyando en la toma de decisiones y definiciones para diseño de informacion y flujos de interaccion. - Desarrollar propuestas creativas para la mejora continua del sitio.', requisitos: 'ultimo año de carrera...')

#Carrera.create(nombre: 'Administracion de Redes Computacionales')
#Carrera.create(nombre: 'Analista Programador Computacional')
#Carrera.create(nombre: 'Tecnico en Telecomunicaciones')
#Carrera.create(nombre: 'Ingenieria en Informatica')
#Carrera.create(nombre: 'Ingenieria en Conectividad y Redes')
#Carrera.create(nombre: 'Diseño industrial')
#Carrera.create(nombre: 'Diseño Grafico')
#Carrera.create(nombre: 'Diseño de vestuario')
#Carrera.create(nombre: 'Diseño de Ambientes')
#Carrera.create(nombre: 'Ilustrador Digital')
#Carrera.create(nombre: 'Relaciones Publicas Mencion Marketing')
#Carrera.create(nombre: 'Tecnico en Diseño Grafico')

#Comuna.create(nombre: 'Peñaflor')
#Comuna.create(nombre: 'Cerro Navia')
#Comuna.create(nombre: 'Conchali')
#Comuna.create(nombre: 'El Bosque')
#Comuna.create(nombre: 'Estacion Central')
#Comuna.create(nombre: 'Huechuraba')
#Comuna.create(nombre: 'Independencia')
#Comuna.create(nombre: 'La Cisterna')
#Comuna.create(nombre: 'La Florida')
#Comuna.create(nombre: 'La Granja')
#Comuna.create(nombre: 'La Pintana')
#Comuna.create(nombre: 'La Reina')
#Comuna.create(nombre: 'Las Condes')
#Comuna.create(nombre: 'Lo Barnechea')
#Comuna.create(nombre: 'Lo Espejo')
#Comuna.create(nombre: 'Lo Prado')
#Comuna.create(nombre: 'Macul')
#Comuna.create(nombre: 'Maipu')
#Comuna.create(nombre: 'Ñuñoa')
#Comuna.create(nombre: 'Padre Hurtado')
#Comuna.create(nombre: 'Pedro Aguirre Cerda')
#Comuna.create(nombre: 'Peñalolen')
#Comuna.create(nombre: 'Pirque')
#Comuna.create(nombre: 'Providencia')
#Comuna.create(nombre: 'Pudahuel')
#Comuna.create(nombre: 'Puente Alto')
#Comuna.create(nombre: 'Quilicura')
#Comuna.create(nombre: 'Quinta Normal')
#Comuna.create(nombre: 'Recoleta')
#Comuna.create(nombre: 'Renca')
#Comuna.create(nombre: 'San Bernardo')
#Comuna.create(nombre: 'San Joaquin')
#Comuna.create(nombre: 'San Jose de Maipo')
#Comuna.create(nombre: 'San Miguel')
#Comuna.create(nombre: 'San Ramon')
#Comuna.create(nombre: 'Santiago')
#Comuna.create(nombre: 'Vitacura')
#Comuna.create(nombre: 'Cerrillos')

#Institucion.create(nombre: 'U. de Chile')
#Institucion.create(nombre: 'P.U. Catolica de Chile')
#Institucion.create(nombre: 'U. de Concepcion')
#Institucion.create(nombre: 'P.U. Catolica de Valparaiso')
#Institucion.create(nombre: 'U. Tecnica Federico Santa Maria')
#Institucion.create(nombre: 'U. de Santiago de Chile')
#Institucion.create(nombre: 'U. Austral de Chile')
#Institucion.create(nombre: 'U. Catolica del Norte')
#Institucion.create(nombre: 'U. de Valparaiso')
#Institucion.create(nombre: 'U.Metropolitana de Cs. de la Educacion')
#Institucion.create(nombre: 'U. Tecnologica Metropolitana')
#Institucion.create(nombre: 'U. de Tarapaca')
#Institucion.create(nombre: 'U. Arturo Prat')
#Institucion.create(nombre: 'U. de Antofagasta')
#Institucion.create(nombre: 'U. de La Serena')
#Institucion.create(nombre: 'U. de Playa Ancha')
#Institucion.create(nombre: 'U. de Atacama')
#Institucion.create(nombre: 'U. del Bio Bio')
#Institucion.create(nombre: 'U. de la Frontera')
#Institucion.create(nombre: 'U. de los Lagos')
#Institucion.create(nombre: 'U. de Magallanes')
#Institucion.create(nombre: 'U. de Talca')
#Institucion.create(nombre: 'U. Catolica del Maule')
#Institucion.create(nombre: 'U. Catolica de la Stma. Concepcion')
#Institucion.create(nombre: 'U. Catolica de Temuco')
#Institucion.create(nombre: 'Universidad Academia de Humanismo Cristiano')
#Institucion.create(nombre: 'Universidad Adolfo Ibañez')
#Institucion.create(nombre: 'Universidad Adventista de Chile')
#Institucion.create(nombre: 'Universidad Alberto Hurtado')
#Institucion.create(nombre: 'Universidad Autonoma de Chile')
#Institucion.create(nombre: 'Universidad Bernardo O Higgins')
#Institucion.create(nombre: 'Universidad Bolivariana')
#Institucion.create(nombre: 'Universidad Catolica Cardenal Raul Silva Henriquez')
#Institucion.create(nombre: 'Universidad Central de Chile')
#Institucion.create(nombre: 'Universidad Chileno - Britanica de Cultura')
#Institucion.create(nombre: 'Universidad de Aconcagua')
#Institucion.create(nombre: 'Universidad de Arte y Ciencias Sociales, ARCIS')
#Institucion.create(nombre: 'Universidad de Artes, Ciencias y Comunicacion, UNIACC')
#Institucion.create(nombre: 'Universidad de Ciencias de la Informatica, UCINF')
#Institucion.create(nombre: 'Universidad de Las Americas')
#Institucion.create(nombre: 'Universidad de Los Andes')
#Institucion.create(nombre: 'Universidad de Rancagua')
#Institucion.create(nombre: 'Universidad de Viña del Mar')
#Institucion.create(nombre: 'Universidad del Desarrollo')
#Institucion.create(nombre: 'Universidad del Mar')
#Institucion.create(nombre: 'Universidad del Pacifico')
#Institucion.create(nombre: 'Universidad Diego Portales')
#Institucion.create(nombre: 'Universidad Finis Terrae')
#Institucion.create(nombre: 'Universidad Gabriela Mistral')
#Institucion.create(nombre: 'Universidad Iberoamericana de Ciencias y Tecnologia UNICIT')
#Institucion.create(nombre: 'Universidad Internacional SEK')
#Institucion.create(nombre: 'Universidad Maritima de Chile')
#Institucion.create(nombre: 'Universidad Mayor')
#Institucion.create(nombre: 'Universidad Miguel de Cervantes')
#Institucion.create(nombre: 'Universidad Nacional Andres Bello')
#Institucion.create(nombre: 'Universidad Pedro de Valdivia')
#Institucion.create(nombre: 'Universidad Regional San Marcos')
#Institucion.create(nombre: 'Universidad San Sebastian')
#Institucion.create(nombre: 'Universidad Santo Tomas')
#Institucion.create(nombre: 'Universidad Tecnologica de Chile - INACAP')
#Institucion.create(nombre: 'Instituto Escuela Moderna de Musica')
#Institucion.create(nombre: 'Instituto Nacional del Futbol')
#Institucion.create(nombre: 'Instituto Profesional AIEP')
#Institucion.create(nombre: 'Instituto Profesional Alpes')
#Institucion.create(nombre: 'Instituto Profesional ARCOS')
#Institucion.create(nombre: 'Instituto Profesional CIISA')
#Institucion.create(nombre: 'Instituto Profesional de Chile')
#Institucion.create(nombre: 'Instituto Profesional de Estudios Bancarios')
#Institucion.create(nombre: 'Instituto Profesional del Valle Central')
#Institucion.create(nombre: 'Instituto Profesional Diego Portales')
#Institucion.create(nombre: 'Instituto Profesional DUOC UC')
#Institucion.create(nombre: 'Instituto Profesional ESUCOMEX')
#Institucion.create(nombre: 'Instituto Profesional INACAP')
#Institucion.create(nombre: 'Instituto Profesional IPLACEX')
#Institucion.create(nombre: 'Instituto Profesional La Araucana')
#Institucion.create(nombre: 'Instituto Profesional Los Leones')
#Institucion.create(nombre: 'Instituto Profesional Luis Galdames')
#Institucion.create(nombre: 'Instituto Profesional Providencia')
#Institucion.create(nombre: 'Instituto profesional Chileno Britanico de Cultura')
#Institucion.create(nombre: 'Organizacion Educacional Diego Portales, Instituto Profesional')
#Institucion.create(nombre: 'Centro de Formacion Tecnica del Medio Ambiente')
#Institucion.create(nombre: 'Centro de Formacion Tecnica, FLOEN')
#Institucion.create(nombre: 'Centro de Formacion Tecnica, ICEL')
#Institucion.create(nombre: 'Centro de Formacion Tecnica, La Place')
#Institucion.create(nombre: 'Centro de Formacion Tecnica, Manpower')
#Institucion.create(nombre: 'Centro de Formacion Tecnica, Simon Bolivar')
#Institucion.create(nombre: 'Centro de Formacion Tecnica, IFE Escuela de Negocios')
#Institucion.create(nombre: 'Centro de Formacion Tecnica, Organizacion Educacional Diego Portales')
